services:
  postgres-db:
    image: postgres:latest
    container_name: my_website_db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-mw_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ['CMD', 'pg_isready', "-q", "-d", "${POSTGRES_DB:-mw_db}", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 10s
      retries: 5
      timeout: 5s

  backend:
    image: my_website_backend:latest
    container_name: my_website_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres-db:5432/${POSTGRES_DB:-mw_db}?sslmode=disable
      MODE: ${MODE:-production}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
