services:
  postgres-db:
    image: postgres:18
    container_name: my_website_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s

  backend:
    image: my_website_backend:latest
    container_name: my_website_backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      postgres-db:
        condition: service_healthy
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env/.env.production
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}?sslmode=disable
      MODE: ${MODE:-production}
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:

